source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
# gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
# gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
# gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
# gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
# gem 'spring',        group: :development
# 
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
gem 'thin'

group :test, :cucumber do
  gem 'rspec', '< 2.98.0'
  gem 'poltergeist'
  gem 'phantomjs'
  gem 'cucumber-rails'
  gem 'capybara', '~> 2.4' # Current Version 2.4.4
  gem 'capybara-webkit'
  gem 'cucumber', '~> 1.3' # Current Version 1.3.7
  gem 'capybara-screenshot', '~> 0.3' # capybara-screenshot-1.0.3, potiential conflict with 'colored' gem, might override rails dependency module.
  gem 'wkhtmltopdf-binary'
  # gem 'pdf-inspector'
  # gem 'pry'
  # gem 'selenium'
  # gem 'selenium-webdriver'
  # # gem 'rubyzip', '1.1.0' # Later versions have uninitialized constant Zip::File (NameError). Can probably remove after combining cukes and app.
  # gem 'headless'
  # gem 'pdf-reader'
  # gem 'database_cleaner'
end
